kind: Service
apiVersion: v1
metadata:
  name: process
  labels:
    expose: 'false'
    funktion.fabric8.io/kind: Function
    runtime: nodejs
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    name: process
